// Cache disabled per user requirement - all data is loaded live from the server
export const cacheService = {
  initCache: async () => false,
  getCourses: () => [],
  getMyCourses: () => [],
  getStudentClasses: () => [],
  getUserProfile: () => null,
  getUserStats: () => null,
  getCourseClasses: () => [],
  getCourseMaterials: () => [],
  setCourses: async () => {},
  setMyCourses: async () => {},
  setStudentClasses: async () => {},
  setUserProfile: async () => {},
  setUserStats: async () => {},
  setCourseClasses: async () => {},
  setCourseMaterials: async () => {},
  prefetchImages: () => {},
  prefetchCachedImages: () => {},
  clearUserCache: async () => {},
};
